DB:
  hostname: 127.0.0.1
  port: 3306
  username: root
  password: sls123
  database: cmdb
  sslmode: disable
  pool_size: 5
  timeout: 500ms
  max_open_conns: 100
  max_idle_conns: 5
# SSH 私钥路径
SSHPrivateKey:
  path: "/Users/wangye/.ssh/id_rsa"